version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartconstruction
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis